BOARD_SIDE_LEN = 15
LETTER_POINTS = {
    'A': 1,
    'B': 3,
    'C': 3,
    'D': 2,
    'E': 1,
    'F': 4,
    'G': 2,
    'H': 4,
    'I': 1,
    'J': 8,
    'K': 5,
    'L': 1,
    'M': 3,
    'N': 1,
    'O': 1,
    'P': 3,
    'Q': 10,
    'R': 1,
    'S': 1,
    'T': 1,
    'U': 1,
    'V': 4,
    'W': 4,
    'X': 8,
    'Y': 4,
    'Z': 10,
    '*': 0
}

BOARD_SCORES = [
    ['TW', 'NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'TW', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS', 'TW'],
    ['NS', 'DW', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'DW', 'NS'],
    ['NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'DL', 'NS', 'DL', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS'],
    ['DL', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'DL'],
    ['NS', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'NS'],
    ['NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS'],
    ['NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'DL', 'NS', 'DL', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS'],
    ['TL', 'NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS', 'TW'],
    ['NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'DL', 'NS', 'DL', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS'],
    ['NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS'],
    ['NS', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'NS'],
    ['DL', 'NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS', 'DL'],
    ['NS', 'NS', 'DW', 'NS', 'NS', 'NS', 'DL', 'NS', 'DL', 'NS', 'NS', 'NS', 'DW', 'NS', 'NS'],
    ['NS', 'DW', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'TL', 'NS', 'NS', 'NS', 'DW', 'NS'],
    ['TW', 'NS', 'NS', 'DL', 'NS', 'NS', 'NS', 'TW', 'NS', 'NS', 'NS', 'DL', 'NS', 'NS', 'TW']
]

LETTER_FREQUENCIES = {
    'A': 9,
    'B': 2,
    'C': 2,
    'D': 4,
    'E': 12,
    'F': 2,
    'G': 3,
    'H': 2,
    'I': 9,
    'J': 1,
    'K': 1,
    'L': 4,
    'M': 2,
    'N': 6,
    'O': 8,
    'P': 2,
    'Q': 1,
    'R': 6,
    'S': 4,
    'T': 6,
    'U': 4,
    'V': 2,
    'W': 2,
    'X': 1,
    'Y': 2,
    'Z': 1,
    '*': 2
}